
CREATE SCHEMA IF NOT EXISTS `<PROJECT_ID>.rides_ops` OPTIONS(location='<REGION>');

CREATE OR REPLACE VIEW `<PROJECT_ID>.rides_ops.vw_dlq_24h` AS
SELECT COUNT(*) AS msgs_24h
FROM `<PROJECT_ID>.rides_ops.dlq_raw`
WHERE _PARTITIONTIME >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR);

CREATE OR REPLACE VIEW `<PROJECT_ID>.rides_ops.vw_dlq_latest` AS
SELECT * FROM `<PROJECT_ID>.rides_ops.dlq_raw`
ORDER BY _PARTITIONTIME DESC
LIMIT 100;
